# Generated by Django 6.0.2 on 2026-02-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_role_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
